import numpy as np
from PIL import Image
import os

def create_sample_image(filename="input.png", width=128, height=128):
    """Creates a sample synthetic image if no image is available."""
    # Create a gradient image with a circle in the center
    y, x = np.ogrid[:height, :width]
    center_y, center_x = height / 2, width / 2
    dist_from_center = np.sqrt((x - center_x)**2 + (y - center_y)**2)
    
    # Gradient + circle pattern
    img_data = (x + y) % 256
    img_data[dist_from_center <= min(width, height) / 4] = 255
    
    img = Image.fromarray(img_data.astype(np.uint8))
    img.save(filename)
    print(f"[Python] Created sample image: {filename}")
    return filename

def preprocess_image(image_path, width=128, height=128):
    """Converts input image to grayscale and resizes it."""
    img = Image.open(image_path).convert('L')
    img = img.resize((width, height))
    return np.array(img, dtype=np.uint8)

def add_salt_and_pepper_noise(image, salt_prob=0.02, pepper_prob=0.02):
    """Adds salt (white pixels) and pepper (black pixels) noise to the image."""
    noisy_image = np.copy(image)
    
    # Salt noise (255)
    num_salt = np.ceil(salt_prob * image.size)
    coords = [np.random.randint(0, i - 1, int(num_salt)) for i in image.shape]
    noisy_image[tuple(coords)] = 255

    # Pepper noise (0)
    num_pepper = np.ceil(pepper_prob * image.size)
    coords = [np.random.randint(0, i - 1, int(num_pepper)) for i in image.shape]
    noisy_image[tuple(coords)] = 0
    
    return noisy_image

def export_image_hex(image, filename="noisy_image.hex"):
    """Exports image array to a ASCII hex format (1 byte / 2 hex digits per line) for FPGA memory initialization."""
    flat_data = image.flatten()
    with open(filename, "w") as f:
        for val in flat_data:
            f.write(f"{val:02X}\n")
    print(f"[Python] Exported noisy image data to: {filename} ({image.shape[1]}x{image.shape[0]} hex values)")

# Backward compatibility alias
export_image_raw = export_image_hex

def import_image_hex(filename, height, width):
    """Imports ASCII hex format generated by C/Hardware program."""
    with open(filename, "r") as f:
        hex_data = [int(line.strip(), 16) for line in f if line.strip()]
    raw_data = np.array(hex_data, dtype=np.uint8)
    return raw_data.reshape((height, width))

# Backward compatibility alias
import_image_raw = import_image_hex

def visualize_results(orig, noisy, denoised, save_path="comparison.png"):
    """Visualizes original, noisy, and denoised images side-by-side using PIL."""
    h, w = orig.shape
    combined = Image.new('L', (w * 3 + 20, h + 30), color=220)
    
    img_orig = Image.fromarray(orig)
    img_noisy = Image.fromarray(noisy)
    img_denoised = Image.fromarray(denoised)
    
    combined.paste(img_orig, (0, 30))
    combined.paste(img_noisy, (w + 10, 30))
    combined.paste(img_denoised, (w * 2 + 20, 30))
    
    combined.save(save_path)
    print(f"[Python] Visual result saved to: {save_path}")

if __name__ == "__main__":
    img_path = "input.png"
    if not os.path.exists(img_path):
        create_sample_image(img_path)
        
    width, height = 128, 128
    
    # 1. Grayscale & Resize
    gray_img = preprocess_image(img_path, width, height)
    
    # 2. Add Salt and Pepper noise
    noisy_img = add_salt_and_pepper_noise(gray_img, salt_prob=0.03, pepper_prob=0.03)
    
    # Export noisy image for C/FPGA memory processing
    export_image_hex(noisy_img, "noisy_image.hex")
